### ISSUE TITLE
Remove all traces of cocoapods.

### ISSUE THREAD

**Issue by kairadiagne** [WeTransfer/UINotifications#68]
As we've recently removed support for cocoapods we can simply remove all traces to it.

**Comment by wetransferplatform** [comment]
The pull request #69 that closed this issue was merged and released as part of [Release 1.7.3](https://github.com/WeTransfer/UINotifications/releases/tag/1.7.3) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
